version: '3'
services:
    web:
        build:
            context: ./docker/web
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        ports:
            - '${APP_PORT:-80}:80'
            - '443:443'
        environment:
            WWWUSER: '${WWWUSER}'
            ENABLE_SSL: ${ENABLE_SSL}
        volumes:
            - '.:/var/www/html'
            - './docker/web/apache/log:/var/log/apache2'
        networks:
            - maclogicss
networks:
    maclogicss:
        driver: bridge
